### ISSUE TITLE
Two implicit assumptions made in the project may cause error when run the example

### ISSUE THREAD

**Issue by PennPanda** [martinamaggio/rt-muse#2]
Hi,

The code is really neat! 👍 

When I tried out the code, I found out the project made two assumptions:
1) On the target machine, rt-muse is under ~/ path.
2)The host machine only has one network card. The LISTENER_IP is automatically parsed the ifconfig output. On a machine with two network cards, the parser for the LISTENER_IP may not work.

These two implicit assumptions do not hold on my computer with mulitple network cards. This make the example does not run smoothly without some debugging effort. 

It may be better to either document these two assumptions or just let user define these two macro. Otherwise, the example in the README may not work as it is. 

Thanks

Meng

**Comment by martinamaggio** [comment]
[This commit ](https://github.com/martinamaggio/rt-muse/commit/7f8db3cebfe19cf504fd1ac89af6413a80334fc7) adds the additional assumptions. In the case of number 1, it is the launcher that downloads rt-muse in the home folder, so the user only need so ensure writing permissions there. In the case of number 2, on the contrary, this may indeed cause troubles. The user may provide a different listener ip (to be added in the next version).
