### ISSUE TITLE
Experiment name does not support hythen 

### ISSUE THREAD

**Issue by PennPanda** [martinamaggio/rt-muse#3]
Hi, 

It seems the experiment name feed into the ./launch.sh does not support "-".
Otherwise, it reports the error as follows:
```

run('/Users/meng/Desktop/github/rt-muse/results/exp-example/exp-example.m')
Error using exp
Not enough input arguments.

Error in run (line 96)
evalin('caller', [script ';']);
```

If needed, I can send a pull request to add this into the README. :-) 

After this, the ./launch.sh runs smoothly.. 👍

**Comment by martinamaggio** [comment]
Thanks @PennPanda. I did not realize that the hyphen would break the parameter list for the script. I am adding this to the README right now and will investigate also a bit more the other issue that you posted - probably I will end up modifying the instructions to include some comments on that too.
